### ISSUE TITLE
Nothing happen after build

### ISSUE THREAD

**Issue by RoxDevvv** [nfynt/AndroidOpenXRLoader#1]
i implemented this loader in my application but nothing happen when run it in android all I see is normal application
do I need to install extra app to be able to see the two eyes like google card runtime
I did search about Monado Runtime for android but I couldn't find any apk's

**Comment by nfynt** [comment]
Hello @RoxDevvv 
This package is a simple loader which is based on [OpenXR specification](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html), for loading your 3rd party android OpenXR runtime. Typically you will need two more applications:
1. XR runtime like Monado, which  is a free and OSS that you can get from [here](https://gitlab.freedesktop.org/monado/monado).
2. A broker app, that will help with the runtime discovery. Again Monado has an open source repo and binaries that you can download from [here](https://gitlab.freedesktop.org/monado/utilities/openxr-android-broker).

You can use any other OpenXR runtime or broker as well. Monado just happens to be the most active and matured one, that I've come across.
